#ifndef NUMERICAL_LINEAR_ALGEBRA_TEST_2_HESSENBERG_QR_H
#define NUMERICAL_LINEAR_ALGEBRA_TEST_2_HESSENBERG_QR_H

namespace NLA {
void Test2HessenbergQR();
} // namespace NLA

#endif //NUMERICAL_LINEAR_ALGEBRA_TEST_2_HESSENBERG_QR_H
