#ifndef NUMERICAL_LINEAR_ALGEBRA_TEST_1_SIMPLE_QR_H
#define NUMERICAL_LINEAR_ALGEBRA_TEST_1_SIMPLE_QR_H

namespace NLA {
void Test1SimpleQR();
} // namespace NLA

#endif //NUMERICAL_LINEAR_ALGEBRA_TEST_1_SIMPLE_QR_H
