#ifndef NUMERICAL_LINEAR_ALGEBRA_TEST_1_RAYLEIGH_QR_H
#define NUMERICAL_LINEAR_ALGEBRA_TEST_1_RAYLEIGH_QR_H

namespace NLA {
void Test1RayleighQR();
} // namespace NLA

#endif //NUMERICAL_LINEAR_ALGEBRA_TEST_1_RAYLEIGH_QR_H
