#ifndef NUMERICAL_LINEAR_ALGEBRA_TEST_1_HESSENBERG_QR_H
#define NUMERICAL_LINEAR_ALGEBRA_TEST_1_HESSENBERG_QR_H

namespace NLA {
void Test1HessenbergQR();
} // namespace NLA

#endif //NUMERICAL_LINEAR_ALGEBRA_TEST_1_HESSENBERG_QR_H
