#ifndef NUMERICAL_LINEAR_ALGEBRA_TEST_2_HESSENBERG_QR_H
#define NUMERICAL_LINEAR_ALGEBRA_TEST_2_HESSENBERG_QR_H

void Test2HessenbergQR();

#endif //NUMERICAL_LINEAR_ALGEBRA_TEST_2_HESSENBERG_QR_H
