#ifndef NUMERICAL_LINEAR_ALGEBRA_TEST_2_RAYLEIGH_QR_H
#define NUMERICAL_LINEAR_ALGEBRA_TEST_2_RAYLEIGH_QR_H

namespace NLA {
void Test2RayleighQR();
} // namespace NLA

#endif //NUMERICAL_LINEAR_ALGEBRA_TEST_2_RAYLEIGH_QR_H
